---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - database.mettle.io
  resources:
  - postgresdatabaseinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.mettle.io
  resources:
  - postgresdatabaseinstances/finalizers
  verbs:
  - update
- apiGroups:
  - database.mettle.io
  resources:
  - postgresdatabaseinstances/status
  verbs:
  - get
  - patch
  - update
